# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{loop_dance}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Danil Pismenny"]
  s.date = %q{2011-01-01}
  s.description = %q{Really simple daemon builder and manager. Based on the looper and daemon_controller}
  s.email = %q{danil@orionet.ru}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/loop_dance.rb",
    "lib/loop_dance/commands.rb",
    "lib/loop_dance/controller.rb",
    "lib/loop_dance/dancer.rb",
    "lib/loop_dance/railtie.rb",
    "lib/loop_dance/task.rb",
    "loop_dance.gemspec",
    "rails/init.rb",
    "spec/dancer_spec.rb",
    "spec/spec_helper.rb",
    "spec/task_spec.rb",
    "tasks/loop_dance.rake",
    "test/rails/.gitignore",
    "test/rails/Gemfile",
    "test/rails/Rakefile",
    "test/rails/app/controllers/application_controller.rb",
    "test/rails/config.ru",
    "test/rails/config/application.rb",
    "test/rails/config/boot.rb",
    "test/rails/config/database.yml",
    "test/rails/config/environment.rb",
    "test/rails/config/environments/development.rb",
    "test/rails/config/environments/production.rb",
    "test/rails/config/environments/test.rb",
    "test/rails/config/initializers/backtrace_silencers.rb",
    "test/rails/config/initializers/inflections.rb",
    "test/rails/config/initializers/mime_types.rb",
    "test/rails/config/initializers/secret_token.rb",
    "test/rails/config/initializers/session_store.rb",
    "test/rails/config/locales/en.yml",
    "test/rails/config/routes.rb",
    "test/rails/db/seeds.rb",
    "test/rails/lib/dancers.rb",
    "test/rails/lib/tasks/.gitkeep",
    "test/rails/public/404.html",
    "test/rails/public/422.html",
    "test/rails/public/500.html",
    "test/rails/public/favicon.ico",
    "test/rails/public/images/rails.png",
    "test/rails/public/index.html",
    "test/rails/public/javascripts/application.js",
    "test/rails/public/javascripts/controls.js",
    "test/rails/public/javascripts/dragdrop.js",
    "test/rails/public/javascripts/effects.js",
    "test/rails/public/javascripts/prototype.js",
    "test/rails/public/javascripts/rails.js",
    "test/rails/public/robots.txt",
    "test/rails/public/stylesheets/.gitkeep",
    "test/rails/script/rails"
  ]
  s.homepage = %q{http://github.com/dapi/loop_dance}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Daemon builder and controller. Easy setup and managed from the rails application or rake tasks. Autostart at rails server startup}
  s.test_files = [
    "spec/dancer_spec.rb",
    "spec/spec_helper.rb",
    "spec/task_spec.rb",
    "test/rails/app/controllers/application_controller.rb",
    "test/rails/config/application.rb",
    "test/rails/config/boot.rb",
    "test/rails/config/environment.rb",
    "test/rails/config/environments/development.rb",
    "test/rails/config/environments/production.rb",
    "test/rails/config/environments/test.rb",
    "test/rails/config/initializers/backtrace_silencers.rb",
    "test/rails/config/initializers/inflections.rb",
    "test/rails/config/initializers/mime_types.rb",
    "test/rails/config/initializers/secret_token.rb",
    "test/rails/config/initializers/session_store.rb",
    "test/rails/config/routes.rb",
    "test/rails/db/seeds.rb",
    "test/rails/lib/dancers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<daemon_controller>, [">= 0.2.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<daemon_controller>, [">= 0.2.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<daemon_controller>, [">= 0.2.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

