# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{loop_dance}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Danil Pismenny"]
  s.date = %q{2010-12-31}
  s.description = %q{Really easy setup. Auto-start daaemon at rails server startup. Rake's tasks based control.}
  s.email = %q{danil@orionet.ru}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/loop_dance.rb",
    "lib/loop_dance/dancer.rb",
    "lib/loop_dance/task.rb",
    "spec/dancer_spec.rb",
    "spec/spec_helper.rb",
    "spec/task_spec.rb"
  ]
  s.homepage = %q{http://github.com/dapi/loop_dance}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple auto-starting daemon based on the looper and daemon_controller}
  s.test_files = [
    "spec/dancer_spec.rb",
    "spec/rails_test/app/controllers/application_controller.rb",
    "spec/rails_test/app/helpers/application_helper.rb",
    "spec/rails_test/config/application.rb",
    "spec/rails_test/config/boot.rb",
    "spec/rails_test/config/environment.rb",
    "spec/rails_test/config/environments/development.rb",
    "spec/rails_test/config/environments/production.rb",
    "spec/rails_test/config/environments/test.rb",
    "spec/rails_test/config/initializers/backtrace_silencers.rb",
    "spec/rails_test/config/initializers/inflections.rb",
    "spec/rails_test/config/initializers/mime_types.rb",
    "spec/rails_test/config/initializers/secret_token.rb",
    "spec/rails_test/config/initializers/session_store.rb",
    "spec/rails_test/config/routes.rb",
    "spec/rails_test/db/seeds.rb",
    "spec/rails_test/lib/dancers.rb",
    "spec/rails_test/test/performance/browsing_test.rb",
    "spec/rails_test/test/test_helper.rb",
    "spec/spec_helper.rb",
    "spec/task_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<daemon_controller>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<daemon_controller>, [">= 0.2.5"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<daemon_controller>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<daemon_controller>, [">= 0.2.5"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<daemon_controller>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<daemon_controller>, [">= 0.2.5"])
  end
end

